services:
  suporteflow:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "10003:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run dev

    networks:
      - suporteflow-network
networks:
  suporteflow-network:
    driver: bridge
