services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - suporteflow-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # Sincroniza as alterações em tempo real
      - /app/node_modules # Cria um volume anônimo para a pasta node_modules, evitando sobreposição com a pasta local
    networks:
      - suporteflow-network

  db:
    image: postgres:17-alpine # Ou mysql:8.0, se preferir MySQL
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # Inicializa o banco (opcional)
    networks:
      - suporteflow-network

volumes:
  db-data:

networks:
  suporteflow-network:
    driver: bridge
