spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/suportflow
    name: suportflow
    username: postgres
    password: PGSuportflow
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: ZXKFvAUFF6NwvQpw0AkzgsTqHT4iQSqb7MkEsTarhPU=
  expirationMs: 86400000
  refreshExpiration: 604800000
admin:
  email: admin@suportflow.com.br
  password: suportflow-admin
logging:
  level:
    root: INFO
    com:
      suportflow: DEBUG
file:
  upload:
    dir: ./tmp/upload
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
