spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/suportflow
    name: suportflow
    username: admin
    password: PGSuportflow
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.ct7vAd_BpNxhgKAhgXNntnXn8_Ek2ZdZOVhQJarEdvE
  expiration: 86400000 # 1 dia em milissegundos (JWT)
  refreshExpiration: 604800000 # 7 dias em milissegundos (Refresh Token)
logging:
  level:
    root: INFO
    com:
      suportflow: DEBUG